# -*- coding: utf-8 -*-
"""Ollama_Server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHdkJDTyJLIn9vSzhAOmLxCASBG4Dfpf
"""

# Credits: Amit Chaudhary (https://github.com/amitness/ollama-remote)

!pip uninstall ollama-remote

!pip install ollama-remote

!ollama-remote